version: "2"
services:

  master:
    image: breeze2/mha4mysql-node:0.57
    container_name: mha_node0
    restart: always
    mem_limit: 256m
    networks:
      net1:
        ipv4_address: 10.5.0.10
    ports:
      - "33060:3306"
    volumes:
      - "./volumes/mha_share/:/root/mha_share/"
      - "./volumes/mha_node0/lib/:/var/lib/mysql/"
      - "./volumes/mha_node0/conf/:/etc/mysql/conf.d/"
    env_file:
      - ./parameters.env
    environment:
      - CONTAINER_NAME=mha_node0

  slave1:
    image: breeze2/mha4mysql-node:0.57
    container_name: mha_node1
    restart: always
    depends_on:
      - master
    mem_limit: 256m
    networks:
      net1:
        ipv4_address: 10.5.0.11
    ports:
      - "33061:3306"
    volumes:
      - "./volumes/mha_share/:/root/mha_share/"
      - "./volumes/mha_node1/lib/:/var/lib/mysql/"
      - "./volumes/mha_node1/conf/:/etc/mysql/conf.d/"
    env_file:
      - ./parameters.env
    environment:
      - CONTAINER_NAME=mha_node1
  slave2:
    image: breeze2/mha4mysql-node:0.57
    container_name: mha_node2
    depends_on:
      - master
    restart: always
    mem_limit: 256m
    networks:
      net1:
        ipv4_address: 10.5.0.12
    ports:
      - "33062:3306"
    volumes:
      - "./volumes/mha_share/:/root/mha_share/"
      - "./volumes/mha_node2/lib/:/var/lib/mysql/"
      - "./volumes/mha_node2/conf/:/etc/mysql/conf.d/"
    env_file:
      - ./parameters.env
    environment:
      - CONTAINER_NAME=mha_node2

  manager:
    image: breeze2/mha4mysql-manager:0.57
    container_name: mha_manager
    depends_on:
      - master
      - slave1
      - slave2
    restart: always
    mem_limit: 256m
    networks:
      net1:
        ipv4_address: 10.5.0.9
    volumes:
      - "./volumes/mha_share/:/root/mha_share/"
      - "./volumes/mha_manager/conf:/etc/mha"
      - "./volumes/mha_manager/work:/usr/local/mha"
    entrypoint: "tailf /dev/null"
    env_file:
      - ./parameters.env
    environment:
      - CONTAINER_NAME=mha_manager
networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
